const char* index_html =
"<!DOCTYPE html>\n"
"<html lang='en'>\n"
"\n"
"<head>\n"
"    <meta charset='UTF-8'>\n"
"    <meta http-equiv='X-UA-Compatible' content='IE=edge'>\n"
"    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
"    <title>CatDrive OTA Update</title>\n"
"    <style>\n"
"        body {\n"
"            font-family: Arial, sans-serif;\n"
"        }\n"
"    </style>\n"
"</head>\n"
"\n"
"<body>\n"
"    <h1>CatDrive OTA Update</h1>\n"
"    <form action='' enctype='multipart/form-data' id='file-form' method='POST'>\n"
"        <div>\n"
"            <p id='progressdiv'><progress max='100' value='0' id='progress' style='display: none;'></progress></p>\n"
"            <input type='file' accept='.bin, .hex' name='file-select' id='file-select'>\n"
"            <button type='submit' id='upload-button'>Upload</button>\n"
"        </div>\n"
"    </form>\n"
"    <script type='text/javascript'>\n"
"        var form = document.getElementById('file-form');\n"
"        var fileSelect = document.getElementById('file-select');\n"
"        var uploadButton = document.getElementById('upload-button');\n"
"\n"
"        form.onsubmit = function (event) {\n"
"            event.preventDefault();\n"
"\n"
"            var progress = document.getElementById('progress');\n"
"            var progressdiv = document.getElementById('progressdiv');\n"
"\n"
"            progress.style.display = 'block';\n"
"            uploadButton.innerHTML = 'Uploading...';\n"
"\n"
"            var files = fileSelect.files;\n"
"            var formData = new FormData();\n"
"            var file = files[0];\n"
"\n"
"            formData.append('file-select', file, file.name);\n"
"\n"
"            var sizeXhr = new XMLHttpRequest();\n"
"            sizeXhr.open('PUT', '/updateFileSize', false);\n"
"            sizeXhr.send('' + file.size);\n"
"            console.log(sizeXhr.status);\n"
"\n"
"            var xhr = new XMLHttpRequest();\n"
"            xhr.open('POST', '/update', true);\n"
"            xhr.upload.onprogress = function (e) {\n"
"                update_progress(e);\n"
"            };\n"
"            xhr.onload = function (e) {\n"
"                if (xhr.status === 200) {\n"
"                    uploadButton.innerHTML = 'Upload';\n"
"                    progressdiv.innerHTML = '<h3 style=\"color: darkgreen;\">Success</h3>';\n"
"                } else {\n"
"                    progressdiv.innerHTML = '<h3 style=\"color: darkred;\">Failed</h3>';\n"
"                }\n"
"            };\n"
"            xhr.send(formData);\n"
"        }\n"
"\n"
"        function update_progress(e) {\n"
"            if (e.lengthComputable) {\n"
"                var percentage = Math.round((e.loaded / e.total) * 100);\n"
"                progress.value = percentage;\n"
"                uploadButton.innerHTML = 'Upload ' + percentage + '%';\n"
"                console.log('Uploading ' + percentage + '%');\n"
"            }\n"
"            else {\n"
"                console.log('Unable to compute progress information since the total size is unknown');\n"
"            }\n"
"        }\n"
"    </script>\n"
"\n"
"</body>\n"
"\n"
"</html>\n"
;